Correction of e_lm, e_glm and e_loess
These three functions were not working when the data contain `NA`s. For example:
```
e <- mtcars %>% 
  mutate(mpg = ifelse(mpg > 20, NA, mpg)) %>%
  e_charts(mpg) %>% 
  e_scatter(qsec)  

e_lm(e, qsec ~ mpg)  

Error: Can't recycle `..1` (size 32) to match `..2` (size 18).
Run `rlang::last_error()` to see where the error occurred.
```
I have included a line with `stats::complete.cases()` to remove the `NA` before using the regression results. Also, when `name = NULL`, the legend was incorrect:
```
e <- mtcars %>% 
  e_charts(mpg) %>% 
  e_scatter(qsec)  

e_lm(e, qsec ~ mpg)  
```
I added `[[i]]` to have a variable name before `-lm` (or `-glm` or `-loess`).